In [162]:
import torch

In [163]:
torch.rand(3)

tensor([0.7654, 0.5221, 0.1035])

In [164]:
#vector
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [165]:
vector.ndim #it counts no of square bracket

1

In [166]:
vector.shape

torch.Size([2])

In [167]:
#matrix
matrix=torch.tensor ([[7,8],[9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [168]:
matrix.ndim

2

In [169]:
matrix.shape

torch.Size([2, 2])

In [170]:
#tensor
tensor=torch.tensor([[[1,2,3],[2,3,4],[5,6,7]]])

In [171]:
tensor

tensor([[[1, 2, 3],
         [2, 3, 4],
         [5, 6, 7]]])

In [172]:
tensor.ndim

3

In [173]:
tensor.shape

torch.Size([1, 3, 3])

In [174]:
tensor[0]

tensor([[1, 2, 3],
        [2, 3, 4],
        [5, 6, 7]])

## random tensors

### random tensors are important bcoz the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random no to better representation of data
start with random no -> loook at data->update random no 

In [175]:
rt1=torch.rand(3,4)
rt1

tensor([[8.5716e-01, 6.4454e-01, 8.1862e-01, 8.9578e-01],
        [5.6421e-01, 4.7478e-01, 4.6540e-01, 5.3096e-01],
        [3.0093e-01, 8.4418e-01, 6.4820e-04, 4.0954e-01]])

In [176]:
rt2=torch.rand(1,3,4)
rt2

tensor([[[0.9654, 0.3858, 0.2607, 0.1341],
         [0.1324, 0.1925, 0.6979, 0.7871],
         [0.1438, 0.7985, 0.5645, 0.8533]]])

In [177]:
rt2.ndim

3

## Creating random tensor with similar shape to an image tensor

In [178]:
random_img_tensor= torch.rand(size=(3,224,224)) #height,width,color channel
random_img_tensor.shape,random_img_tensor.ndim

(torch.Size([3, 224, 224]), 3)

## zeros and ones

In [179]:
z=torch.zeros(3,4)
z

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [180]:
o=torch.ones(3,4)
o

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [181]:
o.dtype

torch.float32

## creating a range of tensors and tensors-like

In [182]:
 #use torch.range()
one_to_ten=torch.range(0,10) #float
one_to_ten

C:\Users\Himani Munjal\AppData\Local\Temp\ipykernel_628\2950550970.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  one_to_ten=torch.range(0,10) #float


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [183]:
one_to_ten1=torch.arange(0,10) #int
one_to_ten1

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [184]:
a=torch.arange(start=5,end=51,step=5)
a

tensor([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [185]:
#create tensors like
z=torch.zeros_like(input=one_to_ten)
z

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

## Tensor Data Types

In [186]:
float_32_tensor=torch.tensor([3.0,6.0,9.0],dtype=None,device=None,requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [187]:
float_32_tensor.dtype

torch.float32

In [188]:
float_16_tensor=float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [189]:
float_16_tensor*float_32_tensor #showing tensor not right dtype

tensor([ 9., 36., 81.])

In [190]:
int_32_tensor=torch.tensor([3,6,9],dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [191]:
float_32_tensor*int_32_tensor

tensor([ 9., 36., 81.])

In [192]:
int_32_tensor=torch.tensor([3,6,9],dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [193]:
float_32_tensor*int_32_tensor

tensor([ 9., 36., 81.])

In [194]:
#creating a new  tensor
t1=torch.rand(3,4)
t1

tensor([[0.2569, 0.4703, 0.1939, 0.2529],
        [0.3501, 0.0070, 0.4830, 0.5334],
        [0.8531, 0.9968, 0.1391, 0.0290]])

In [195]:
print(t1)
print(f"Datatype of tensor :{t1.dtype}")
print(f"Shape of tensor : {t1.shape}")
print(f"Device tensor is on :{t1.device}")

tensor([[0.2569, 0.4703, 0.1939, 0.2529],
        [0.3501, 0.0070, 0.4830, 0.5334],
        [0.8531, 0.9968, 0.1391, 0.0290]])
Datatype of tensor :torch.float32
Shape of tensor : torch.Size([3, 4])
Device tensor is on :cpu


##   Manipulating Tensors

In [196]:
#Addition
t2=torch.tensor([1,2,3])
t2+100

tensor([101, 102, 103])

In [197]:
#multiplication
t2*5

tensor([ 5, 10, 15])

In [198]:
# Subtraction
t2-5

tensor([-4, -3, -2])

In [199]:
 #Inbuilt functions
t2.mul(10)

tensor([10, 20, 30])

In [200]:
t2.add(5)

tensor([6, 7, 8])

## Matrix Multiplication
two ways of performing multiplication in NN and Dl are:
 
1.Element -wis multiplication (scalar)

2.Matrix multiplication (dot product)

In [201]:
#element-wise multiplication
print(t2,"*",t2)
print(f"Equals:{t2*t2}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals:tensor([1, 4, 9])


In [202]:
#matrix multiplication
torch.matmul(t2,t2)

tensor(14)

In [203]:
import time
## Calculating time
%%time
value=0
for i in range(len(t2)):
    value+=t2[i]*t2[i]
print(value)    

UsageError: Line magic function `%%time` not found.


In [204]:
t3=torch.tensor([[1,2],[3,4],[5,6]])
t3

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [205]:
#transpose
t3.T

tensor([[1, 3, 5],
        [2, 4, 6]])

## finding the min,max,mean,sum,etc (tensor aggregation)

In [206]:
#create a tensor
x=torch.arange(0,100,10)
x


tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [207]:
x.dtype

torch.int64

In [208]:
#MIN
x.min()

tensor(0)

In [209]:
x.max()

tensor(90)

In [210]:
#mean: torch.mean() requires a tensor of float32 datatype to work 
torch.mean(x.type(torch.float32))

tensor(45.)

In [211]:
x.type(torch.float32).mean()

tensor(45.)

In [212]:
#sum
x.sum()

tensor(450)

## Finding the positional max and min

In [213]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [214]:
#finding the position in tensor having minimum value
x.argmin()

tensor(0)

In [215]:
#finding the position in tensor having minimum value
x.argmax()

tensor(9)

## Reshaping, stacking, squeezing and unsqueezing tensors

Reshaping : reshapes an input tensor to a defined shape

View : Return a view of an input tensor of certain shape but keep the same memory as the original tensor

Stacking : combine multiple tensors on top of each other (vstack) or side by side (hstack)

Squeeze:removes all dimensions from a tensor

Unsqueeze : add a 1 dimension to a farget tensor

Permute : Return a view of the input with dimensions permuted (swapped) in a certain way

In [216]:
#reshaping i.e adding an extra dimension
p=torch.arange(1.,10.)
p,p.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [217]:
p1=p.reshape(3,3)
p1

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [218]:
p1.shape

torch.Size([3, 3])

In [219]:
#change the view
z=p.view(3,3)
z,z.shape


(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [220]:
#changing z changes p (because a view of tensor shares the same memory as the original tensor)
z[:,0]=5
z,p

(tensor([[5., 2., 3.],
         [5., 5., 6.],
         [5., 8., 9.]]),
 tensor([5., 2., 3., 5., 5., 6., 5., 8., 9.]))

In [221]:
#stack tensors on each other  #hstack
p_stacked=torch.stack([p,p,p,p],dim=1) #column-wise
p_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [5., 5., 5., 5.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [222]:
#vstacked
p_stacked=torch.stack([p,p,p,p],dim=0) #row-wise
p_stacked

tensor([[5., 2., 3., 5., 5., 6., 5., 8., 9.],
        [5., 2., 3., 5., 5., 6., 5., 8., 9.],
        [5., 2., 3., 5., 5., 6., 5., 8., 9.],
        [5., 2., 3., 5., 5., 6., 5., 8., 9.]])

In [223]:
#torch.squeeze()-removes all 1-d from a target tensor
p2=p.reshape(1,9)

In [224]:
p2 #2 [] brackets

tensor([[5., 2., 3., 5., 5., 6., 5., 8., 9.]])

In [225]:
p3=p2.squeeze() #only 1 square bracket

In [226]:
p3.shape 

torch.Size([9])

In [227]:
#torch.unsqueeze()-adds a single dimension to a target tensor at a specific dimension
print(f"Previous target :{p3}")
print(f"Previous Shape:{p3.shape}")

#adding an extra dimension with unsqueeze


Previous target :tensor([5., 2., 3., 5., 5., 6., 5., 8., 9.])
Previous Shape:torch.Size([9])


In [228]:
p3=p3.unsqueeze(dim=0)
print(f"New Tensor:{p3}")
print(f"New Shape : {p3.shape}")


New Tensor:tensor([[5., 2., 3., 5., 5., 6., 5., 8., 9.]])
New Shape : torch.Size([1, 9])


In [229]:
#torch.permute-rearranges the dimensions of a target tensor in a specified order
a=torch.rand(size=(224,224,3)) #[height,width,color_channels[RGB]]
#permuting the original tensor
a1=a.permute(2,0,1) #shifts 2->0,0->2,1->2
print(f"Previous vector :{a}")
print(f"Permutted vector :{a1}")
print(f"Previous shape :{a.shape}")
print(f"New shape :{a1.shape}")

Previous vector :tensor([[[0.7391, 0.5843, 0.8528],
         [0.8443, 0.7829, 0.9966],
         [0.6518, 0.6017, 0.2997],
         ...,
         [0.6619, 0.8361, 0.2176],
         [0.7800, 0.9781, 0.8040],
         [0.6697, 0.2907, 0.4922]],

        [[0.5241, 0.2531, 0.1101],
         [0.1135, 0.0568, 0.9647],
         [0.4118, 0.1094, 0.2204],
         ...,
         [0.7048, 0.5260, 0.5608],
         [0.0714, 0.5688, 0.0323],
         [0.9604, 0.1502, 0.9047]],

        [[0.4486, 0.7292, 0.9764],
         [0.6293, 0.1895, 0.2567],
         [0.2530, 0.0600, 0.6314],
         ...,
         [0.1089, 0.0648, 0.5489],
         [0.4882, 0.5773, 0.6892],
         [0.5059, 0.3014, 0.8555]],

        ...,

        [[0.5653, 0.4319, 0.1248],
         [0.4295, 0.6371, 0.2755],
         [0.7647, 0.0287, 0.4543],
         ...,
         [0.3547, 0.5778, 0.7894],
         [0.9906, 0.0866, 0.7449],
         [0.1281, 0.5615, 0.6607]],

        [[0.0045, 0.5231, 0.6107],
         [0.2606, 0.9488, 0.93

## Indexing in pytorch is same as numpy

## PyTorch tensors & NumPy

NumPy is a popular scientific Python numerical computing library.
And because of this, PyTorch has functionality to interact with it

• Data in NumPy, want in PyTorch tensor -> torch.from_numpy(ndarray)

• PyTorch tensor -> NumPy-> torch.Tensor.numpy()

In [230]:
import numpy as np
array=np.arange(1.0,10.0)
tensor=torch.from_numpy(array) #coverting from array to tensor,tensor will show the default data type of float64 unless specified
array,tensor

(array([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64))

In [231]:
array.dtype,tensor.dtype

(dtype('float64'), torch.float64)

In [232]:
# Change in value of array,won't make the change in tensor
array=array+1
array,tensor

(array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64))

In [233]:
#Tensor to numpy array
tensor=torch.ones(7)
numpy_tensor=tensor.numpy()
tensor,numpy_tensor


(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [234]:
# Change in value of tensor,won't make the change in numpy
tensor=tensor+1
tensor,numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

• Reproducbility (trying to take random out of random)

In short how a neural network learns:

start with random numbers -> tensor operations -> update random numbers to try and make them of the data -> again -> again -> again...

To reduce the randomness in neural networks and PyTorch comes the concept of a random seed.

Essentially what the random seed does is "flavour the randomness.

In [235]:
#creating 2 random tensors
tensor1=torch.rand(3,4)
tensor2=torch.rand(3,4)
print(tensor1)
print(tensor2)
print(tensor1==tensor2)

tensor([[0.2782, 0.6928, 0.6242, 0.2090],
        [0.6243, 0.5980, 0.2872, 0.9383],
        [0.2353, 0.6341, 0.8737, 0.1922]])
tensor([[0.4210, 0.3270, 0.5539, 0.4931],
        [0.3210, 0.7458, 0.9195, 0.8807],
        [0.8865, 0.5596, 0.2012, 0.3478]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [236]:
#let's make random but reproducible tensors
#set the random seed
RANDOM_SEED=42
torch.manual_seed(RANDOM_SEED)
tensor3=torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
tensor4=torch.rand(3,4)

print(tensor3)
print(tensor4)
print(tensor3==tensor4)


tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
