## RAND(), RANDN(), RANF() AND RANDINT() FUNCITONS IN RANDOM MODULE 

In [1]:
import numpy as np

In [2]:
a=np.random.rand(3,4) #rand shows value between [0,1)

In [3]:
a

array([[0.21844374, 0.87139113, 0.04227854, 0.48407461],
       [0.80469179, 0.65561278, 0.4664099 , 0.26514859],
       [0.44890608, 0.84760496, 0.64173552, 0.48991846]])

In [4]:
b=np.random.randn(2,4) #randn shows standard values

In [5]:
b

array([[ 0.08541939, -0.01399548, -0.02895622,  1.28745025],
       [-0.27203112, -0.84075426, -0.77568843, -0.89178092]])

In [9]:
c=np.random.ranf(2) #only 1 argument is passed into it
# returns float value between (0,1]
c

array([0.95653147, 0.6732827 ])

In [10]:
c=c=np.random.ranf(2,7) #showing error
c 

TypeError: random_sample() takes at most 1 positional argument (2 given)

In [12]:
d=np.random.randint(1,5,size=4) # here 1 is inclusive & 5 is exclusive
d

array([2, 1, 1, 3])

In [13]:
e=np.random.randint(1,6,size=(2,4)) #size can be given in tuple too
e

array([[3, 4, 3, 2],
       [2, 5, 4, 4]])

In [17]:
f=np.random.randint(111) #if high is not present;interval would be 0 to low
f

110

In [18]:
g=np.random.randint(111,size=6)
g

array([28, 99, 69, 28, 64, 24])