In [1]:
import numpy as np


## Applying functions on random array

In [4]:
# Creating a random matrix
matrix_a = np.random.rand(3, 4)
matrix_a

array([[0.93869188, 0.78701698, 0.26013903, 0.11394764],
       [0.02106251, 0.89824123, 0.9720571 , 0.13105605],
       [0.22490788, 0.80217867, 0.3955477 , 0.72625397]])

In [5]:
# Apply element-wise operation
result = np.exp(matrix_a)
result


array([[2.55663484, 2.19683344, 1.29711041, 1.12069345],
       [1.0212859 , 2.45528103, 2.64337655, 1.14003168],
       [1.25220735, 2.23039492, 1.48519742, 2.06732183]])

In [7]:
matrix_b = np.random.rand(4, 2)
#matrix multplication
result_matrix = np.dot(matrix_a, matrix_b)
result_matrix 

array([[1.8255626 , 1.16038389],
       [1.50277249, 0.9599521 ],
       [1.75685699, 1.32614123]])

## Creating different types of Arrays

In [9]:
# Create a 1D array
array_1d = np.array([1, 2, 3])
array_1d

array([1, 2, 3])

In [10]:
# Create a 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
array_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
# Create a random  matrix
random_matrix = np.random.rand(3, 3)
random_matrix

array([[0.3602281 , 0.12595068, 0.54816078],
       [0.15950364, 0.14486236, 0.49703655],
       [0.01594866, 0.63242835, 0.42427087]])


## Performing Operations

In [14]:
#addition
array_a = np.array([1, 2, 3])
array_b = np.array([4, 5, 6])
result_addition = array_a + array_b
result_addition

array([5, 7, 9])

In [15]:
#subtraction
array_a = np.array([1, 2, 3])
array_b = np.array([4, 5, 6])
result_subtraction = array_a - array_b
result_subtraction

array([-3, -3, -3])

In [16]:
#multipliction
array_a = np.array([1, 2, 3])
array_b = np.array([4, 5, 6])
result_m = array_a * array_b
result_m

array([ 4, 10, 18])

In [17]:
#multipliction
array_a = np.array([1, 2, 3])
array_b = np.array([4, 5, 6])
array_c=np.array([1,2,3])
result_m = array_a * array_b*array_c
result_m

array([ 4, 20, 54])

In [18]:
# Matrix multiplication
matrix_a = np.random.rand(3, 4)
matrix_b = np.random.rand(4, 2)
result_matrix = np.dot(matrix_a, matrix_b)
result_matrix

array([[1.48382513, 2.14873398],
       [0.60233177, 1.73082052],
       [0.61484294, 0.87174712]])

In [20]:
#bitwise or
a=5
b=7
c=np.bitwise_or(a,b)
c


7

## new additional functions of python

In [23]:
#arr2string (represent an array as a string)

# Create a NumPy array
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Convert the array to a string
arr_string = np.array2string(arr)

print(arr_string)

[[1 2 3]
 [4 5 6]]


In [26]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array2string(a)
print(b)


[[1 2 3]
 [4 5 6]]


In [28]:
import numpy as np

# Create a NumPy array
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Convert the array to a string with custom formatting
arr_string = np.array2string(arr, separator=', ', prefix='Array: ', formatter={'int': '{:02}'.format})

print(arr_string)


[[01, 02, 03],
        [04, 05, 06]]


In [31]:
#arange function
x  = np.arange(3.)
print(x)


[0. 1. 2.]


## using lambda with array2string ,formattting that

In [32]:
np.array2string(x, formatter={'float_kind':lambda x: "%.2f" % x})


'[0.00 1.00 2.00]'

In [33]:
x  = np.arange(3)
np.array2string(x, formatter={'int':lambda x: hex(x)})



'[0x0 0x1 0x2]'

In [36]:
# Transpose matrices
matrix = np.random.rand(3, 3)
transposed_matrix = np.transpose(matrix)
transposed_matrix


array([[0.45735514, 0.96629961, 0.52729852],
       [0.09491574, 0.66166267, 0.49872935],
       [0.54682665, 0.7873927 , 0.26895866]])

In [35]:
#inverse matrix 
inverted_matrix = np.linalg.inv(matrix)
inverted_matrix

array([[-3.20252904,  0.97232111,  2.82243515],
       [ 0.95699222,  3.40887447, -5.49741348],
       [ 1.84382122, -2.78521268,  2.57457287]])

In [38]:
# Broadcasting with advanced shapes
#using newaxis (used to l increase the dimensions of array by one dimension)
matrix = np.random.rand(3, 1)
scalar = np.array([1, 2, 3])
result= matrix + scalar[:, np.newaxis]
result

array([[1.69056901],
       [2.15367651],
       [3.13113788]])

In [40]:
# Singular Value Decomposition (SVD)
matrix = np.random.rand(3, 3)
U, S, V = np.linalg.svd(matrix)
print(U,S,V)

[[-0.33550103  0.22794832  0.9140452 ]
 [-0.84655562  0.35269471 -0.39868537]
 [-0.41325857 -0.90754945  0.07464149]] [1.15711869 0.39243668 0.11229331] [[-0.30641649 -0.63979976 -0.70481572]
 [ 0.15832883  0.69586232 -0.70050525]
 [-0.9386378   0.32623901  0.11192494]]
