In [1]:
import torch

In [2]:
torch.rand(3)

tensor([0.3679, 0.9199, 0.3426])

In [3]:
#vector
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [4]:
vector.ndim #it counts no of square bracket

1

In [5]:
vector.shape

torch.Size([2])

In [6]:
#matrix
matrix=torch.tensor ([[7,8],[9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [7]:
matrix.ndim

2

In [9]:
matrix.shape

torch.Size([2, 2])

In [10]:
#tensor
tensor=torch.tensor([[[1,2,3],[2,3,4],[5,6,7]]])

In [11]:
tensor

tensor([[[1, 2, 3],
         [2, 3, 4],
         [5, 6, 7]]])

In [12]:
tensor.ndim

3

In [13]:
tensor.shape

torch.Size([1, 3, 3])

In [14]:
tensor[0]

tensor([[1, 2, 3],
        [2, 3, 4],
        [5, 6, 7]])

## random tensors

### random tensors are important bcoz the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random no to better representation of data
start with random no -> loook at data->update random no 

In [15]:
rt1=torch.rand(3,4)
rt1

tensor([[0.4999, 0.3470, 0.2231, 0.0571],
        [0.9513, 0.5747, 0.3543, 0.1273],
        [0.1378, 0.8124, 0.3345, 0.0057]])

In [17]:
rt2=torch.rand(1,3,4)
rt2

tensor([[[0.9767, 0.7194, 0.9280, 0.1765],
         [0.0993, 0.0771, 0.1607, 0.8654],
         [0.5417, 0.0603, 0.1175, 0.2790]]])

In [18]:
rt2.ndim

3

## Creating random tensor with similar shape to an image tensor

In [20]:
random_img_tensor= torch.rand(size=(3,224,224)) #height,width,color channel
random_img_tensor.shape,random_img_tensor.ndim

(torch.Size([3, 224, 224]), 3)

## zeros and ones

In [22]:
z=torch.zeros(3,4)
z

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
o=torch.ones(3,4)
o

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [24]:
o.dtype

torch.float32

## creating a range of tensors and tensors-like

In [27]:
 #use torch.range()
one_to_ten=torch.range(0,10) #float
one_to_ten

C:\Users\Himani Munjal\AppData\Local\Temp\ipykernel_9040\1487560189.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  one_to_ten=torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [28]:
one_to_ten1=torch.arange(0,10) #int
one_to_ten1

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
a=torch.arange(start=5,end=51,step=5)
a

tensor([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [31]:
#create tensors like
z=torch.zeros_like(input=one_to_ten)
z

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

## Tensor Data Types

In [35]:
float_32_tensor=torch.tensor([3.0,6.0,9.0],dtype=None,device=None,requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [36]:
float_32_tensor.dtype

torch.float32

In [37]:
float_16_tensor=float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [38]:
float_16_tensor*float_32_tensor #showing tensor not right dtype

tensor([ 9., 36., 81.])

In [39]:
int_32_tensor=torch.tensor([3,6,9],dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [40]:
float_32_tensor*int_32_tensor

tensor([ 9., 36., 81.])

In [41]:
int_32_tensor=torch.tensor([3,6,9],dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [42]:
float_32_tensor*int_32_tensor

tensor([ 9., 36., 81.])

In [43]:
#creating a new  tensor
t1=torch.rand(3,4)
t1

tensor([[0.2121, 0.4490, 0.8073, 0.1506],
        [0.7740, 0.0892, 0.8401, 0.9394],
        [0.9815, 0.0497, 0.4902, 0.3994]])

In [44]:
print(t1)
print(f"Datatype of tensor :{t1.dtype}")
print(f"Shape of tensor : {t1.shape}")
print(f"Device tensor is on :{t1.device}")

tensor([[0.2121, 0.4490, 0.8073, 0.1506],
        [0.7740, 0.0892, 0.8401, 0.9394],
        [0.9815, 0.0497, 0.4902, 0.3994]])
Datatype of tensor :torch.float32
Shape of tensor : torch.Size([3, 4])
Device tensor is on :cpu


##   Manipulating Tensors

In [45]:
#Addition
t2=torch.tensor([1,2,3])
t2+100

tensor([101, 102, 103])

In [46]:
#multiplication
t2*5

tensor([ 5, 10, 15])

In [47]:
# Subtraction
t2-5

tensor([-4, -3, -2])

In [49]:
 #Inbuilt functions
t2.mul(10)

tensor([10, 20, 30])

In [50]:
t2.add(5)

tensor([6, 7, 8])