# Numpy Practise for CogniTv

In [1]:
import numpy as np

## Q. Rehapimg an array with unkown dimension using -1 and understanding where clause

In [2]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.where(arr %2 == 1 ,-1,arr)

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [17]:
arr.reshape(2,-1) # Using -1 will automatically calculate the possible size

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Q. Convert the function maxx that works on two scalars, to work on two arrays

In [22]:
pair_max = np.vectorize(max, otypes=[int])

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

pair_max(a, b)


array([6, 7, 9, 8, 9, 7, 5])

## Q. Swap columns 1 and 2 in the array arr.

In [27]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [28]:
arr[:, [1,0,2]]   # Swap Columns

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [30]:
arr[[1,0,2], :]    # Swap row

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

## Q. How to import a dataset with numbers and texts keeping the text intact in python numpy

In [31]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

In [33]:
iris = np.genfromtxt(url, delimiter=',', dtype='object')

In [37]:
iris[:5]

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa'],
       [b'4.6', b'3.1', b'1.5', b'0.2', b'Iris-setosa'],
       [b'5.0', b'3.6', b'1.4', b'0.2', b'Iris-setosa']], dtype=object)

In [38]:
iris.shape

(150, 5)

## Q. Extract the text column species from the 1D iris imported in previous question.

names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')


In [40]:
species = np.array([row[4] for row in iris])

In [41]:
species[:5]

array([b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa'], dtype='|S15')

## Q. Convert the 1D iris to 2D array iris_2d by omitting the species text field.

In [43]:
# Method 1: Convert each row to a list and get the first 4 items
iris_2d = np.array([row.tolist()[:4] for row in iris])
iris_2d[:4]

array([[b'5.1', b'3.5', b'1.4', b'0.2'],
       [b'4.9', b'3.0', b'1.4', b'0.2'],
       [b'4.7', b'3.2', b'1.3', b'0.2'],
       [b'4.6', b'3.1', b'1.5', b'0.2']], dtype='|S3')

In [44]:
# Alt Method 2: Import only the first 4 columns from source url
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[:4]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2]])