# Numpy Practise for CogniTv

In [1]:
import numpy as np

## 1. Multiplication of Matrix Using Numpy

In [3]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[3,2,1],[6,5,4],[9,8,7]])

In [17]:
print("A - ")
print(a)
print("B - ")
print(b)

A - 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
B - 
[[3 2 1]
 [6 5 4]
 [9 8 7]]


In [8]:
print(a.shape)
print(a.shape)

(3, 3)
(3, 3)


In [13]:
a*b # Give elemnt wise Multiplication

array([[ 3,  4,  3],
       [24, 25, 24],
       [63, 64, 63]])

In [11]:
a.dot(b) # Give matrix Multiplication

array([[ 42,  36,  30],
       [ 96,  81,  66],
       [150, 126, 102]])

In [14]:
np.matmul(a,b) # Give matrix multiplication using built-in function of Numpy

array([[ 42,  36,  30],
       [ 96,  81,  66],
       [150, 126, 102]])

## 2. Create programme to change a string element in a specified Numpy array to Uppercase, lowercase, capitalize the first letter, title case and swap case.

In [20]:
my_arr = np.array(["I","love","kishangarh"])

In [21]:
type(my_arr)

numpy.ndarray

In [22]:
my_arr.shape

(3,)

In [23]:
upper_arr = np.char.upper(my_arr)

In [26]:
print(upper_arr)

['I' 'LOVE' 'KISHANGARH']


In [27]:
lower_arr = np.char.lower(my_arr)

In [28]:
print(lower_arr)

['i' 'love' 'kishangarh']


In [31]:
capitalize_arr = np.char.capitalize(my_arr)
print(capitalize_arr)

['I' 'Love' 'Kishangarh']


In [32]:
title_arr = np.char.title(my_arr)
print(title_arr)

['I' 'Love' 'Kishangarh']


In [33]:
swap_arr = np.char.swapcase(my_arr)
print(swap_arr)

['i' 'LOVE' 'KISHANGARH']


In [37]:
np.char.capitalize(["hello to the world"])

array(['Hello to the world'], dtype='<U18')

In [38]:
np.char.title(["hello to the world"])

array(['Hello To The World'], dtype='<U18')

## 3. How to find a generate a row number of a Numpy Array if any element is larger value than a specified value

In [39]:
arr = np.array([[1,2,3,4,5],[10,-3,40,32,9],[3,6,2,8,5],[11,2,1,4,3],[9,8,7,6,5]])

In [40]:
x = 10

In [41]:
arr

array([[ 1,  2,  3,  4,  5],
       [10, -3, 40, 32,  9],
       [ 3,  6,  2,  8,  5],
       [11,  2,  1,  4,  3],
       [ 9,  8,  7,  6,  5]])

In [47]:
np.any(arr > x,axis = 1)  # any give boolean reply

array([False,  True, False,  True, False])

In [45]:
np.where(np.any(arr > x,axis = 1))

(array([1, 3], dtype=int64),)

In [46]:
arr[np.any(arr > x,axis = 1)]

array([[10, -3, 40, 32,  9],
       [11,  2,  1,  4,  3]])

## 4. How to remove rows which contains Null values in a Numpy Array

In [49]:
narr = np.array([[10.5,2.5,4.6,1.2,8.9],[23,4,11,34,56],[78,34,np.nan,23,51],[34,12,23,44,55]])

In [53]:
print(narr)
print("Shape :",narr.shape)

[[10.5  2.5  4.6  1.2  8.9]
 [23.   4.  11.  34.  56. ]
 [78.  34.   nan 23.  51. ]
 [34.  12.  23.  44.  55. ]]
Shape : (4, 5)


In [58]:
narr[np.isnan(narr).any(axis = 1)] # Returm boolean

array([[78., 34., nan, 23., 51.]])

In [61]:
narr[~np.isnan(narr).any(axis = 1)] # Returm boolean

array([[10.5,  2.5,  4.6,  1.2,  8.9],
       [23. ,  4. , 11. , 34. , 56. ],
       [34. , 12. , 23. , 44. , 55. ]])

## 5.  How to multiply string element in a Numpy Array

In [62]:
3*"Apple"

'AppleAppleApple'

In [64]:
sarr = np.array(['Nisarg','Nitin','Akash','Mayank'])

In [66]:
sarr

array(['Nisarg', 'Nitin', 'Akash', 'Mayank'], dtype='<U6')

In [69]:
nsarr = np.char.multiply(sarr,3)
print(nsarr)

['NisargNisargNisarg' 'NitinNitinNitin' 'AkashAkashAkash'
 'MayankMayankMayank']


## 6. How to select minimum value along the rows in Numpy Array

In [70]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [71]:
a.shape

(3, 3)

In [77]:
np.apply_along_axis(lambda x: np.min(x),arr = a,axis = 0)  # From Column

array([1, 2, 3])

In [76]:
np.apply_along_axis(lambda x: np.min(x),arr = a,axis = 1)  # From Row 

array([1, 4, 7])

## 7. How to replace diagonal value with a number of a Numpy Array

In [82]:
darr = np.array([[1,2,3],[4,5,6],[7,8,9]])
darr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [79]:
x = 5

In [81]:
for i in range(len(darr)):     # BRUTE METHOD
    for j in range(len(darr[i])):
        if i == j:
            darr[i][j] = x
darr

array([[5, 2, 3],
       [4, 5, 6],
       [7, 8, 5]])

In [84]:
np.fill_diagonal(darr,x)

In [85]:
darr

array([[5, 2, 3],
       [4, 5, 6],
       [7, 8, 5]])

## 8. How to check the number is present in Numpy array and fill all the negative values with another number

In [86]:
 arrr = np.array([12,34,-1,4,-23,43,25,-3,42,9])

In [87]:
arrr

array([ 12,  34,  -1,   4, -23,  43,  25,  -3,  42,   9])

In [92]:
np.isin(arrr,[12,3,43])

array([ True, False, False, False, False,  True, False, False, False,
       False])

In [95]:
arrr[arrr<0] = 8

In [96]:
arrr

array([12, 34,  8,  4,  8, 43, 25,  8, 42,  9])

## 9. How to use reshape numpy array. And create new numpy array

In [98]:
m_arr = np.arange(16)

In [100]:
len(m_arr)

16

In [102]:
m_arr = m_arr.reshape(4,4)

In [103]:
m_arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [104]:
new_arr = m_arr[::-1]

In [106]:
new_arr

array([[12, 13, 14, 15],
       [ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [ 0,  1,  2,  3]])

## 10. Use of numpy pad function in Numpy array. How to add padding / border to a matrix 

In [109]:
ar = np.ones((2,2))
ar

array([[1., 1.],
       [1., 1.]])

In [110]:
np.pad(ar,pad_width = 1,mode = 'constant',constant_values= 0)

array([[0., 0., 0., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 0., 0., 0.]])

## 11. Calculate sin and cos values of the numbers given in the array

In [111]:
ar = np.array([0,30,45,60,90])

In [112]:
np.sin(ar) # expect input in radians.

array([ 0.        , -0.98803162,  0.85090352, -0.30481062,  0.89399666])

In [118]:
sar = ar * np.pi / 180  # to convert degree to radians
sar

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [119]:
np.sin(sar)

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [120]:
np.cos(sar)

array([1.00000000e+00, 8.66025404e-01, 7.07106781e-01, 5.00000000e-01,
       6.12323400e-17])

## 12.  How to remove one dimensional array in Numpy using Squeeze function and check whether number is present in the array

In [122]:
ar = np.array([[[1,2,3],[4,5,6],[7,8,9]]])

In [123]:
ar.shape

(1, 3, 3)

In [127]:
nar =  np.squeeze(ar) # remoove extra dimension

In [128]:
nar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [129]:
nar.shape

(3, 3)

In [132]:
print(7 in nar)
print(12 in nar)
print(3 in nar)
print(9 in nar)

True
False
True
True


## 13. Compare two numpy arrays

In [133]:
a= np.array([121,23,45])
b = np.array([234,12,42])

In [134]:
a>b

array([False,  True,  True])

In [135]:
np.greater(a,b)

array([False,  True,  True])

In [136]:
a >= b

array([False,  True,  True])

In [137]:
np.greater_equal(a,b)

array([False,  True,  True])

In [138]:
np.less_equal(a,b)

array([ True, False, False])

In [139]:
a<=b

array([ True, False, False])

## 14. How to stack two arrays

In [141]:
a = np.arange(10).reshape(2,5)
b = np.arange(10,20).reshape(2,5)

In [142]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [143]:
b

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [144]:
np.concatenate([a,b],axis = 1)

array([[ 0,  1,  2,  3,  4, 10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9, 15, 16, 17, 18, 19]])

In [145]:
np.concatenate([a,b],axis = 0)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [147]:
np.hstack([a,b])

array([[ 0,  1,  2,  3,  4, 10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9, 15, 16, 17, 18, 19]])

In [148]:
np.vstack([a,b])

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [149]:
np.c_[a,b]

array([[ 0,  1,  2,  3,  4, 10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9, 15, 16, 17, 18, 19]])

In [150]:
np.r_[a,b]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

## 15. How to put values from a Numpy array over another numpy array at certain positions

In [151]:
arr1 = np.array([23,12,45,7,65,90])

In [152]:
print(arr1)

[23 12 45  7 65 90]


In [154]:
arr2 = np.array([4,5,6])

In [155]:
print(arr2)

[4 5 6]


In [156]:
arr1.put([1,3,5],arr2)

In [157]:
arr1

array([23,  4, 45,  5, 65,  6])

In [158]:
arr2

array([4, 5, 6])

## 16. Numpy Delete function and Insert function

In [173]:
ar = np.ones([3,3])
print(ar)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [174]:
column = np.array([10,11,12])

In [175]:
ar = np.delete(ar,[1],axis=1)

In [176]:
print(ar)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [178]:
np.insert(ar,1,column,axis=1)

array([[ 1., 10.,  1.],
       [ 1., 11.,  1.],
       [ 1., 12.,  1.]])

## 17. How to write a program to create an array of 10 zeros, 10 ones, 10 fives

In [190]:
ar1 = np.ones(10)
ar2 = np.zeros(10)
ar3 = np.ones(10)*5

In [191]:
ar1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [192]:
ar2

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [193]:
ar3

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

## 18.  How to create random sequences with different functions like Numpy repeat function, Numpy tile and Numpy Concatenate

In [194]:
a = np.array([1,2,3])

In [195]:
a

array([1, 2, 3])

In [198]:
b = np.repeat(a,3)

In [199]:
c = np.tile(a,3)

In [200]:
np.concatenate([b,c])

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

## 19. How to create a Numpy array and determine the memory size of the Numpy array

In [201]:
arr = np.array([1,7,13,105])

In [202]:
print(arr)

[  1   7  13 105]


In [203]:
arr.itemsize

4

In [204]:
arr.size

4

In [205]:
arr.size * arr.itemsize

16