# Numpy Practise for CogniTv

In [41]:
import numpy as np

In [4]:
n1 = np.full((6,6),5)
n2 = np.zeros((6,6))
print(n1,n2)
print(type(n1))


[[5 5 5 5 5 5]
 [5 5 5 5 5 5]
 [5 5 5 5 5 5]
 [5 5 5 5 5 5]
 [5 5 5 5 5 5]
 [5 5 5 5 5 5]] [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
<class 'numpy.ndarray'>


In [5]:
type(n2)

numpy.ndarray

In [6]:
n6 = np.full((3,6),(9))
n6

array([[9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9]])

In [7]:
n7 = np.arange(10,20)
n7

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [8]:
n8 = np.arange(10,55,5)

In [9]:
n8

array([10, 15, 20, 25, 30, 35, 40, 45, 50])

In [10]:
n9 = np.random.randint(1,100,5)
n9

array([ 1,  5, 84,  3, 67])

In [11]:
b = np.array([[1,23,4,5,5],[56,8,9,4,6]])

In [12]:
b.shape

(2, 5)

In [13]:
b

array([[ 1, 23,  4,  5,  5],
       [56,  8,  9,  4,  6]])

In [14]:
b.shape= (5,2)

In [15]:
b

array([[ 1, 23],
       [ 4,  5],
       [ 5, 56],
       [ 8,  9],
       [ 4,  6]])

In [16]:
b.shape = (10,1)

In [17]:
b

array([[ 1],
       [23],
       [ 4],
       [ 5],
       [ 5],
       [56],
       [ 8],
       [ 9],
       [ 4],
       [ 6]])

In [18]:
a = np.array([10,30,8,99])
b = np.array([23,55,67,9])

In [19]:
np.vstack((a,b))

array([[10, 30,  8, 99],
       [23, 55, 67,  9]])

In [20]:

np.hstack((a,b))

array([10, 30,  8, 99, 23, 55, 67,  9])

In [21]:
np.column_stack((a,b))

array([[10, 23],
       [30, 55],
       [ 8, 67],
       [99,  9]])

In [22]:
a = np.array([10,20,30,40,50,60])
b = np.array([50,60,70,80,90,100])

In [23]:
np.intersect1d(a,b)

array([50, 60])

In [24]:
np.setdiff1d(a,b)

array([10, 20, 30, 40])

In [25]:
np.setdiff1d(b,a)

array([ 70,  80,  90, 100])

In [26]:
np.sum([a,b])

660

In [27]:
np.sum([a,b],axis=0)

array([ 60,  80, 100, 120, 140, 160])

In [28]:
np.sum([a,b],axis=1)

array([210, 450])

In [29]:
a = a /5
a

array([ 2.,  4.,  6.,  8., 10., 12.])

In [30]:
a

array([ 2.,  4.,  6.,  8., 10., 12.])

In [31]:
b

array([ 50,  60,  70,  80,  90, 100])

In [32]:
np.mean(b)

75.0

In [34]:
np.median(b)

75.0

In [35]:
np.std(b)

17.07825127659933

In [36]:
np.std(b) * 3

51.234753829797995

In [37]:
b

array([ 50,  60,  70,  80,  90, 100])